[phases.setup]
nixPkgs = ["php", "php.packages.composer", "nodejs_18", "npm"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm ci"
]

[phases.build]
cmds = [
  "npm run build"
]

[phases.start]
cmds = [
  "php artisan serve --host=0.0.0.0 --port=$PORT"
]
